/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        vsc: {
          bg: 'var(--vsc-bg)',
          chrome: 'var(--vsc-chrome)',
          side: 'var(--vsc-side)',
          activity: 'var(--vsc-activity)',
          border: 'var(--vsc-border)',
          text: 'var(--vsc-text)',
          muted: 'var(--vsc-muted)',
          accent: 'var(--vsc-accent)',
          'accent-hover': 'var(--vsc-accent-hover)',
          'accent-text': 'var(--vsc-accent-text)',
          hover: 'var(--vsc-hover)',
          active: 'var(--vsc-active)',
          'active-text': 'var(--vsc-active-text)',
          input: 'var(--vsc-input)',
          'input-border': 'var(--vsc-input-border)',
          btn: 'var(--vsc-btn)',
          'btn-hover': 'var(--vsc-btn-hover)',
          btn2: 'var(--vsc-btn2)',
          'btn2-hover': 'var(--vsc-btn2-hover)',
          status: 'var(--vsc-status)',
          'status-hover': 'var(--vsc-status-hover)',
          term: 'var(--vsc-term)',
          green: 'var(--vsc-green)',
          yellow: 'var(--vsc-yellow)',
          red: 'var(--vsc-red)',
          orange: 'var(--vsc-orange)',
          gray: 'var(--vsc-gray)',
          cyan: 'var(--vsc-cyan)',
          violet: 'var(--vsc-violet)',
          blue: 'var(--vsc-blue)',
          amber: 'var(--vsc-amber)',
          'cyan-dim': 'var(--vsc-cyan-dim)',
          'red-dim': 'var(--vsc-red-dim)',
        },
      },
    },
  },
  plugins: [],
}
